when:
  - event: push
    branch: [main, woodpecker]
  - event: pull_request

steps:
  test:py312:
    image: docker.io/python:3.12
    commands:
      - apt-get update
      # cmake, libgirepository1.0-dev: required for building pygobject
      - apt-get -y install iproute2 cmake libgirepository1.0-dev
      - rm -f .coverage* collected-coverage
      - pip install tox
      # Separate run so I don't waste time telling errors in setup apart from errors at runtime
      - tox --notest --skip-env '^py31[^2]'
      - "AIOCOAP_TEST_MCIF=\"$(ip -j -6 route list default | python3 -c 'import sys, json; print(json.load(sys.stdin)[0][\"dev\"])')\" tox --skip-env '^py31[^2]'"
      - mkdir collected-coverage/tox-3.12/ -p
      - mv .coverage* collected-coverage/tox-3.12/
