when:
  - event: push
    branch: [main, woodpecker]
  - event: pull_request

steps:
  test:bullseye:
    depends_on: []
    image: docker.io/debian:bullseye
    commands:
      - rm -f .coverage* collected-coverage
      - apt-get update
      - apt-get -y install tox build-essential python3-dev libssl-dev autoconf python3-setuptools python3-pip iproute2
      - pip3 install --upgrade setuptools
      # Separate run so I don't waste time telling errors in setup apart from errors at runtime
      - tox --notest
      - "AIOCOAP_TEST_MCIF=\"$(ip -j -6 route list default | python3 -c 'import sys, json; print(json.load(sys.stdin)[0][\"dev\"])')\" tox"

#   test:py311:
#     image: docker.io/debian:bookworm
#     group: tests
#     commands:
#       - set -x
#       - apt-get update && apt-get -y install iproute2 socat
#       - ip -4 a; ip -6 a; ip -6 r
#       - 'timeout 2m socat -v -v - tcp6-listen:1234,bind=::ffff:127.0.0.1'
